// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AppMain: typeof import('./src/components/Layout/components/AppMain.vue')['default']
    Breadcrumb: typeof import('./src/components/Breadcrumb/index.vue')['default']
    ElBreadcrumb: typeof import('element-plus/es')['ElBreadcrumb']
    ElBreadcrumbItem: typeof import('element-plus/es')['ElBreadcrumbItem']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    Hamburger: typeof import('./src/components/Hamburger/index.vue')['default']
    Item: typeof import('./src/components/Layout/components/Sidebar/Item.vue')['default']
    Layout: typeof import('./src/components/Layout/index.vue')['default']
    Link: typeof import('./src/components/Layout/components/Sidebar/Link.vue')['default']
    Logo: typeof import('./src/components/Layout/components/Sidebar/Logo.vue')['default']
    Navbar: typeof import('./src/components/Layout/components/Navbar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ScrollPane: typeof import('./src/components/Layout/components/TagsView/ScrollPane.vue')['default']
    Settings: typeof import('./src/components/Layout/components/Settings/index.vue')['default']
    Sidebar: typeof import('./src/components/Layout/components/Sidebar/index.vue')['default']
    SidebarItem: typeof import('./src/components/Layout/components/Sidebar/SidebarItem.vue')['default']
    TagsView: typeof import('./src/components/Layout/components/TagsView/index.vue')['default']
  }
}
